modified index.html and index.css files
chilara/my-website pull request #1
Opened 2022-06-03 08:43 UTC by chilara

done

2022-06-03 08:52 UTC, andrewinsoul requested changes

2022-06-03 08:52 UTC, andrewinsoul commented on index.css
> +
h1, h5 and h4 have similar styles. A more concise way of styling them is:
h1, h5, h4 {
   color: #ffffff
}

2022-06-03 13:43 UTC, chilara commented
Roger that boss.



On Fri, 3 Jun 2022 at 9:52 AM, Okoye Andrew ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In index.css
> <https://github.com/chilara/my-website/pull/1#discussion_r888755795>:
>
> > +
> +h1{
> +    color: #ffffff;
> +
> +}
> +
> +h5{
> +    color: #ffffff;
> +
> +}
> +
> +h4{
> +    color: #ffffff;
> +
> +}
> +
>
> h1, h5 and h4 have similar styles. A more concise way of styling them is:
> h1, h5, h4 {
> color: #ffffff
> }
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chilara/my-website/pull/1#pullrequestreview-994643976>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVIFG3VYN5HOEJLZMFEPEU3VNHBWVANCNFSM5XXZYTVQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-11 01:54 UTC, andrewinsoul approved these changes
u can now merge

2022-06-11 01:54 UTC, andrewinsoul approved these changes

2022-06-11 01:55 UTC, chilara commented
Awesome, thanks!

On Fri, Jun 10, 2022 at 6:54 PM Okoye Andrew ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> u can now merge
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chilara/my-website/pull/1#pullrequestreview-1003411565>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVIFG3VLRCK54JGD5742EWDVOPWUZANCNFSM5XXZYTVQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-11 01:57 UTC, merged